# Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [20]:
import numpy as np

values = np.zeros((8, 8))

for i in range(0, 8):
    if i % 2 == 0:
         for j in range(0, 7, 2):
              values[i][j] = 1
    else:
         for j in range(1, 8, 2):
              values[i][j] = 1

print(values)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arange.

In [52]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

for i in range(0, 5):
    arr[i] = np.arange(0, 5)

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [35]:
import numpy as np

arr = np.random.random((3, 3, 3))

print(arr)

[[[0.11211815 0.84844591 0.43641374]
  [0.58953069 0.03328144 0.04036239]
  [0.37750517 0.43099354 0.08279812]]

 [[0.31466972 0.5280905  0.24180574]
  [0.31160533 0.33966489 0.20060891]
  [0.82730018 0.06288799 0.20318366]]

 [[0.86313698 0.57037418 0.57565354]
  [0.9108754  0.22787158 0.54923685]
  [0.77673538 0.36687065 0.41410978]]]


# Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.


In [51]:
import numpy as np

arr = np.ones((10, 10))
arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [56]:
import numpy as np

arr = np.random.random(10)

print('Отсортированный по убыванию массив:', np.sort(arr)[::-1])

Отсортированный по убыванию массив: [0.93840367 0.86515914 0.85569763 0.80936562 0.68537305 0.54566596
 0.51196098 0.4476931  0.26677827 0.15094116]


# Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [1]:
import numpy as np

arr = np.ones((5, 5))

print('Матрица:\n', arr, '\nФорма матрицы:', arr.shape, '\nРазмер матрицы:', arr.size, '\nРазмерность матрицы:', arr.ndim)

Матрица:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
Форма матрицы: (5, 5) 
Размер матрицы: 25 
Размерность матрицы: 2


# Задание 2.3.1

Найти евлидово расстояние  между двумя Series(точками) a и b, не используя встроенную формулу

In [5]:
import pandas as pd
import math as m

a = pd.Series([0, 1, 1], ['x', 'y', 'z'])
b = pd.Series([1, 1, 0], ['x', 'y', 'z'])

res = m.sqrt((a['x']-b['x'])**2 + (a['y']-b['y'])**2 + (a['z']-b['z'])**2)

print(res)

1.4142135623730951


# Задание 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets)

In [8]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)


In [13]:
"""
Задание 2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.
"""

display(dataframe.head(4))
display(dataframe.tail(6))
display(dataframe.shape)
display(dataframe.describe())

display(dataframe.iloc[1:11])

display(dataframe[dataframe['Age'] >= 20].head(10))

Name PClass   Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.0  female   
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1

Name PClass   Age     Sex  Survived  SexCode
1307     Zabour, Miss Tamini    3rd   NaN  female         0        1
1308      Zakarian, Mr Artun    3rd  27.0    male         0        0
1309  Zakarian, Mr Maprieder    3rd  26.0    male         0        0
1310        Zenni, Mr Philip    3rd  22.0    male         0        0
1311        Lievens, Mr Rene    3rd  24.0    male         0        0
1312          Zimmerman, Leo    3rd  29.0    male         0        0

(1313, 6)

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

Name PClass    Age     Sex  \
1                     Allison, Miss Helen Loraine    1st   2.00  female   
2             Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3   Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                   Allison, Master Hudson Trevor    1st   0.92    male   
5                              Anderson, Mr Harry    1st  47.00    male   
6                Andrews, Miss Kornelia Theodosia    1st  63.00  female   
7                          Andrews, Mr Thomas, jr    1st  39.00    male   
8    Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
9                          Artagaveytia, Mr Ramon    1st  71.00    male   
10                      Astor, Colonel John Jacob    1st  47.00    male   

    Survived  SexCode  
1          0        1  
2          0        0  
3          0        1  
4          1        0  
5          1        0  
6          1        1  
7          0        0  
8          1        1  
9          0        0  
10         0        0

Name PClass   Age     Sex  \
0                     Allen, Miss Elisabeth Walton    1st  29.0  female   
2              Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3    Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   
5                               Anderson, Mr Harry    1st  47.0    male   
6                 Andrews, Miss Kornelia Theodosia    1st  63.0  female   
7                           Andrews, Mr Thomas, jr    1st  39.0    male   
8     Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.0  female   
9                           Artagaveytia, Mr Ramon    1st  71.0    male   
10                       Astor, Colonel John Jacob    1st  47.0    male   
15  Baxter, Mrs James (Helene DeLaudeniere Chaput)    1st  50.0  female   

    Survived  SexCode  
0          1        1  
2          0        0  
3          0        1  
5          1        0  
6          1        1  
7          0        0  
8          1        1  
9          0        0  
10         0        0  
15         1        1

# Задание 3.3

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [17]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

minMax = MinMaxScaler()
std = StandardScaler()

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
arr = pd.read_csv(url)
display(arr.head(5))

arr[['sepal_length_cm']] = minMax.fit_transform(arr[['sepal_length_cm']])
arr[['sepal_width_cm']] = std.fit_transform(arr[['sepal_length_cm']])

arr.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222       -0.900681              1.4             0.2  setosa
1         0.166667       -1.143017              1.4             0.2  setosa
2         0.111111       -1.385353              1.3             0.2  setosa
3         0.083333       -1.506521              1.5             0.2  setosa
4         0.194444       -1.021849              1.4             0.2  setosa